theme: minima
avatar: "https://avatars1.githubusercontent.com/u/46810101?s=60&v=4"
title: Vidya Vuruputoor

markdown: kramdown
gems: 
  - jekyll-feed
   
exclude:  
  - Gemfile
  - Gemfile.lock
  - README.md
