theme: jekyll-theme-minima
name: Vidya Vuruputoor
description: Keep an eye out for my project updates!
avatar: images/headshot.jpg

footer-links:
  dribbble:
  email: <vidya.vuruputoor@uconn.edu>
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin: https://www.linkedin.com/in/vidya-vuruputoor/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: vuruputoor
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

